---
- name: "Creates directory"
  file:
    path: /home/ubuntu/backend
    state: directory
    
- name: "Move backend files to remote server."
  become: true
  copy:
    src: /root/project/backend
    dest: /home/ubuntu

- name: "Install dependencies"
  shell: |
    cd /home/ubuntu/backend   
    npm install

- name: Build
  become: true
  shell: | 
    export ENVIRONMENT=production
    export NODE_ENV=production
    export TYPEORM_CONNECTION="{{ lookup('env', 'TYPEORM_CONNECTION') }}"
    export TYPEORM_HOST="{{ lookup('env', 'TYPEORM_HOST') }}"
    export TYPEORM_MIGRATIONS_DIR="{{ lookup('env', 'TYPEORM_MIGRATIONS_DIR') }}"
    export TYPEORM_MIGRATIONS="{{ lookup('env', 'TYPEORM_MIGRATIONS') }}"
    export TYPEORM_PORT="{{ lookup('env', 'TYPEORM_PORT') }}"
    export TYPEORM_ENTITIES=./modules/domain/**/*.entity\{.ts,.js\}
    export TYPEORM_USERNAME="{{ lookup('env', 'TYPEORM_USERNAME') }}"
    export TYPEORM_PASSWORD="{{ lookup('env', 'TYPEORM_PASSWORD') }}"
    export TYPEORM_DATABASE="{{ lookup('env', 'TYPEORM_DATABASE') }}"
    cd /home/ubuntu/backend
    npm run build

- name: Run Migrations
  become: true
  shell: | 
    export ENVIRONMENT=production
    export NODE_ENV=production
    export TYPEORM_CONNECTION="{{ lookup('env', 'TYPEORM_CONNECTION') }}"
    export TYPEORM_HOST="{{ lookup('env', 'TYPEORM_HOST') }}"
    export TYPEORM_MIGRATIONS_DIR="{{ lookup('env', 'TYPEORM_MIGRATIONS_DIR') }}"
    export TYPEORM_MIGRATIONS="{{ lookup('env', 'TYPEORM_MIGRATIONS') }}"
    export TYPEORM_PORT="{{ lookup('env', 'TYPEORM_PORT') }}"
    export TYPEORM_ENTITIES=./modules/domain/**/*.entity\{.ts,.js\}
    export TYPEORM_USERNAME="{{ lookup('env', 'TYPEORM_USERNAME') }}"
    export TYPEORM_PASSWORD="{{ lookup('env', 'TYPEORM_PASSWORD') }}"
    export TYPEORM_DATABASE="{{ lookup('env', 'TYPEORM_DATABASE') }}"
    cd /home/ubuntu/backend
    npm run migrations

- name: "run server"
  become: true
  shell: |
    export ENVIRONMENT=production
    export NODE_ENV=production
    export TYPEORM_CONNECTION="{{ lookup('env', 'TYPEORM_CONNECTION') }}"
    export TYPEORM_HOST="{{ lookup('env', 'TYPEORM_HOST') }}"
    export TYPEORM_MIGRATIONS_DIR="{{ lookup('env', 'TYPEORM_MIGRATIONS_DIR') }}"
    export TYPEORM_MIGRATIONS="{{ lookup('env', 'TYPEORM_MIGRATIONS') }}"
    export TYPEORM_PORT="{{ lookup('env', 'TYPEORM_PORT') }}"
    export TYPEORM_ENTITIES=./modules/domain/**/*.entity\{.ts,.js\}
    export TYPEORM_USERNAME="{{ lookup('env', 'TYPEORM_USERNAME') }}"
    export TYPEORM_PASSWORD="{{ lookup('env', 'TYPEORM_PASSWORD') }}"
    export TYPEORM_DATABASE="{{ lookup('env', 'TYPEORM_DATABASE') }}"
    cd /home/ubuntu/backend
    pm2 start npm -- run start